#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         4
bspc config window_gap          20

bspc config top_padding 15

bspc config border_radius 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#a52654"
bspc config normal_border_color "#120a12"



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Fix java issues
wmname LG3D &

# Restore Wallpaper
nitrogen --restore &

# Launch Picom
picom --experimental-backends --backend glx 

# Launch Polybar
$HOME/.config/polybar/launch.sh
